- type: job
  id: Dockhand
  name: job-name-dockhand
  description: job-description-dockhand
  playTimeTracker: JobDockhand
  startingGear: ContractorGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-gliess
  accessGroups:
  - GeneralAccess
  access:
  - GliessSheriff

  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-ind-dockhand
      - type: LanguageAdder
        addSpoken:
          - Tradeband
        addUnderstood:
          - Tradeband

- type: startingGear
  id: ContractorGear
  equipment:
    ears: ClothingHeadsetGrey
    id: DockhandPDA
    jumpsuit: ClothingUniformSpacer
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorBlack
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
