- type: job
  id: Dockhand
  name: job-name-dockhand
  description: job-description-dockhand
  playTimeTracker: JobDockhand
  requirements:
  - !type:CharacterOverallTimeRequirement
    min: 3600
  startingGear: ContractorGear
  icon: "JobIconDockhand"
  supervisors: job-supervisors-gliess

  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-ind-dockhand
      - type: LanguageAdder
        addSpoken:
          - Tradeband
        addUnderstood:
          - Tradeband
    accessGroups:
  - GeneralAccess
  access:
  - GliessSheriff

- type: startingGear
  id: ContractorGear
  equipment:
    ears: ClothingHeadsetGrey
    id: DockhandPDA
    jumpsuit: ClothingUniformSpacer
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorBlack
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
