- type: job
  id: ConscriptShipCaptainNCWL
  name: job-name-conscript-ncwl-ship-captain
  description: job-description-conscript-ncwl-ship-captain
  playTimeTracker: ConscriptJobShipCaptainNCWL
  requirements:
    - !type:FactionRequirement
      factionID: "NCWL"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - ForeignerLight
        - Muted
        - Blindness
        - Pacifist
        - WheelchairBound
  weight: 55
  startingGear: ConscriptShipCaptainNCWLGear
  alwaysUseSpawner: true
  icon: "JobIconCommsOfficer"
  requireAdminNotify: true
  supervisors: job-supervisors-highcomm
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-kapitan
  access:
  - EmergencyShuttleRepealAll
  - Captain
  - HeadOfPersonnel
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfSecurity
  - ResearchDirector
  - Frontier # Frontier
  - Command
  - Cryogenics
  - Security
  - Detective
  - Armory
  - Brig
  - Lawyer
  - Engineering
  - Mail # Frontier
  - Medical
  - Mercenary # Frontier
  - Quartermaster
  - Salvage
  - Cargo
  - Research
  - Service
  - StationTrafficController # Frontier
  - Maintenance
  - External
  - Janitor
  - Theatre
  - Bar
  - Chemistry
  - Kitchen
  - Chapel
  - Hydroponics
  - Atmospherics
  - Command
  - Maintenance
  - NCWLGeneral
  - Service
  - NCWLKommissar
  - NCWLJail
  - NCWLArmory
  - NCWLCommand
  - External
  - Captain # Frontier

- type: startingGear
  id: ConscriptShipCaptainNCWLGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitNCWLCommunications
    neck: ClothingNeckIFFOrange
    id: AdministratorPDA
    ears: ClothingHeadsetNCWL
    shoes: ClothingShoesBootsJack
    outerClothing: ClothingOuterCoatJacketJamrock
    head: ClothingHeadHatNCWLBeretAdmiral
    belt: ClothingBeltAssaultFilledCrew #looks better
    pocket1: EmergencyOxygenTankFilled
    back: ClothingBackpackNCWL
  inhand:
    - WeaponPistolT91
