- type: job
  id: ConscriptRiflemanNCWL
  name: job-name-conscript-ncwl-rifleman
  description: job-description-conscript-ncwl-rifleman #change me later
  playTimeTracker: ConscriptJobRiflemanNCWL
  weight: 10
  startingGear: ConscriptRiflemanNCWLGear
  alwaysUseSpawner: true
  icon: "JobIconSanitar"
  requirements:
    - !type:FactionRequirement
      factionID: "NCWL"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - Muted
        - WheelchairBound
  requireAdminNotify: false
  supervisors: job-supervisors-highcomm
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-partisan
  access:
  - Command
  - Maintenance
  - Service
  - NCWLGeneral
  - NCWLJail
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  - NCWLAdministrator
  - NCWLFunds
  - NCWLKommissar
  - NCWLArmory
  - NCWLCommand

- type: startingGear
  id: ConscriptRiflemanNCWLGear
  equipment:
    head: ClothingHeadHelmetNCWLBasic
    mask: ClothingMaskPilot
    jumpsuit: ClothingUniformJumpsuitNCWL
    outerClothing: ClothingOuterArmorNCWLHeavyCarapace
    shoes: ClothingShoesBootsJack
    belt: ClothingBeltNCWLPouchesFilledRifleman
    back: WeaponSniperNCWLNovomosin
    pocket1: EmergencyOxygenTankFilled
    pocket2: GrenadeShrapnel
    ears: ClothingHeadsetNCWL
    id: SanitarPDA
    suitstorage: WeaponPistolComrade
