- type: job
  id: ConscriptSniperNCWL
  name: job-name-conscript-ncwl-amr
  description: job-description-conscript-ncwl-amr #change me later
  playTimeTracker: ConscriptJobSniperNCWL
  weight: 10
  startingGear: ConscriptSniperNCWLGear
  alwaysUseSpawner: true
  icon: "JobIconCommsOfficer"
  requirements:
    - !type:FactionRequirement
      factionID: "NCWL"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - Muted
        - WheelchairBound
  requireAdminNotify: false
  supervisors: job-supervisors-highcomm
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-specialist
  access:
  - Command
  - Maintenance
  - Service
  - NCWLGeneral
  - NCWLJail
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  - NCWLAdministrator
  - NCWLFunds
  - NCWLKommissar
  - NCWLArmory
  - NCWLCommand

- type: startingGear
  id: ConscriptSniperNCWLGear
  equipment:
    head: ClothingHeadHelmetNCWLBasic
    neck: ClothingNeckIFFOrange
    mask: ClothingMaskSyndicateFacemask
    jumpsuit: ClothingUniformJumpsuitNCWL
    outerClothing: ClothingOuterArmorNCWLHeavyCarapace
    shoes: ClothingShoesBootsJack
    belt: ClothingBeltNCWLPouchesFilledSniper
    back: ClothingBackpackNCWL
    pocket1: EmergencyOxygenTankFilled
    pocket2: SmokeGrenade
    ears: ClothingHeadsetNCWL
    eyes: ClothingEyesGlassesCheapSunglassesBig
    id: SanitarPDA
    suitstorage: WeaponAntimaterielNCWLHayha
  inhand:
    - WeaponPistolT91